[package]
name = "rustsvp"
version = "1.0.0"
edition = "2024"
description = "A speed reading RSVP application"
authors = ["Louis Lesniak <Wirenux>"]

license = "MIT"

readme = "README.md"
repository = "https://github.com/Wirenux/rustsvp" # Replace with your repo link
keywords = ["rsvp", "speed-reading", "egui", "gui"]
categories = ["gui"]

exclude = ["TODO.todo", "text.txt", "images/"]

[dependencies]
eframe = "0.36.1"
rfd = "0.17.2"
image = { version = "0.25", default-features = false, features = ["png"] }

[package.metadata.packager]
product-name = "RustSVP"
identifier = "com.wirenux.rustsvp"
category = "Education"
icons = ["assets/icon.icns", "assets/icon.ico", "assets/icon.png"]
